### ISSUE TITLE
新增物種 lysimachia ravenni

### ISSUE THREAD

**Issue by lyh-yihsuan** [TaiBIF/apg4#9]
_lysimachia ravenni_ C. I Peng, sp. nov 大漢山珍珠菜

特有種
發表於台灣原生植物誌全圖鑑 第六卷 p.112

**Comment by mutolisp** [comment]
加到 TaiCOL 資料庫中了

| TaiCOL id | cname   | scientific name | source | endemic/naturalized | IUCN category |
| -- | ------- | --------------- | ------- | -------------------- | -------- |
|  [434270](http://taibnet.sinica.edu.tw/chi/taibnet_species_detail.php?name_code=434270) | 大漢山珍珠菜 | _Lysimachia ravenii_ C.I. Peng | 臺灣原生植物全圖鑑第六卷, 2018 | Native | |
